# Generated by Django 5.0.6 on 2024-05-24 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_location_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodTypes',
            new_name='FoodType',
        ),
    ]
