# Generated by Django 5.0.6 on 2024-05-24 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_rename_foodtypes_foodtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.foodtype')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.location')),
                ('place_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.placetype')),
            ],
        ),
    ]
